"""Fix ALL corrupted Jinja2 templates"""
import os

TEMPLATE_DIR = r"Backend\Documents\templates"

# ===================== PROFESSIONAL REPORT =====================
professional_report = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Professional Report</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>{{ css_content }}</style>
    {% if accent_color %}
    <style>:root { --primary: {{ accent_color }}; --primary-dark: {{ accent_color }}; }</style>
    {% endif %}
</head>
<body>
    <div class="document">
        <div class="cover-page">
            <h1 class="title">{{ title }}</h1>
            {% if subtitle %}<p class="subtitle">{{ subtitle }}</p>{% endif %}
            <div class="brand-accent"></div>
            <div class="meta">
                <p class="author">{{ author | default("Kai AI") }}</p>
                <p class="date">{{ date }}</p>
            </div>
        </div>

        {% for section in sections %}
        <div class="section">
            {% if section.heading %}<h2>{{ section.heading }}</h2>{% endif %}
            <div class="section-content">
                {% if section.type == "paragraph" %}
                    <p>{{ section.content | safe }}</p>
                {% elif section.type == "bullets" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.items %}
                    <ul class="bullet-list">
                        {% for item in section.items %}<li>{{ item | safe }}</li>{% endfor %}
                    </ul>
                    {% endif %}
                {% elif section.type == "table" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.data and section.data | length > 0 %}
                    <table>
                        <thead><tr>{% for h in section.data[0] %}<th>{{ h }}</th>{% endfor %}</tr></thead>
                        <tbody>{% for row in section.data[1:] %}<tr>{% for cell in row %}<td>{{ cell }}</td>{% endfor %}</tr>{% endfor %}</tbody>
                    </table>
                    {% endif %}
                {% elif section.type == "highlight" %}
                    <div class="highlight-box"><p>{{ section.content | safe }}</p></div>
                {% else %}
                    <p>{{ section.content | safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% if highlights and highlights | length > 0 %}
        <div class="section">
            <h2>Key Takeaways</h2>
            <div class="section-content">
                <div class="highlight-box">
                    {% for highlight in highlights %}<div class="highlight-item">{{ highlight }}</div>{% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="document-footer">
            <p>{{ footer_text | default("Generated by Kai AI") }}</p>
        </div>
    </div>
</body>
</html>'''

# ===================== PITCH DOCUMENT =====================
pitch_document = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Pitch Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>{{ css_content }}</style>
    {% if accent_color %}
    <style>:root { --primary: {{ accent_color }}; --primary-dark: {{ accent_color }}; }</style>
    {% endif %}
</head>
<body>
    <div class="document">
        <div class="cover-page">
            <h1 class="title">{{ title }}</h1>
            {% if tagline %}<p class="tagline">"{{ tagline }}"</p>{% endif %}
            <div class="brand-accent"></div>
            <div class="meta">
                <p class="author">{{ author | default("Kai AI") }}</p>
                <p class="date">{{ date }}</p>
            </div>
        </div>

        {% if vision %}
        <div class="section">
            <h2>Vision</h2>
            <div class="section-content">
                <div class="highlight-box"><p style="font-size: 1.2rem; font-style: italic;">{{ vision }}</p></div>
            </div>
        </div>
        {% endif %}

        {% if problem_statement %}
        <div class="section">
            <h2>The Problem</h2>
            <div class="section-content"><p>{{ problem_statement }}</p></div>
        </div>
        {% endif %}

        {% if solution_overview %}
        <div class="section">
            <h2>Our Solution</h2>
            <div class="section-content"><p>{{ solution_overview }}</p></div>
        </div>
        {% endif %}

        {% if key_features and key_features | length > 0 %}
        <div class="section">
            <h2>What We Offer</h2>
            <div class="section-content">
                <ul class="bullet-list">
                    {% for feature in key_features %}<li>{{ feature }}</li>{% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% if market_size %}
        <div class="section">
            <h2>Market Opportunity</h2>
            <div class="section-content"><div class="highlight-box"><p>{{ market_size }}</p></div></div>
        </div>
        {% endif %}

        {% if traction and traction | length > 0 %}
        <div class="section">
            <h2>Traction & Milestones</h2>
            <div class="section-content">
                <ul class="bullet-list">
                    {% for item in traction %}<li>{{ item }}</li>{% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% for section in sections %}
        <div class="section">
            {% if section.heading %}<h2>{{ section.heading }}</h2>{% endif %}
            <div class="section-content">
                {% if section.type == "paragraph" %}
                    <p>{{ section.content | safe }}</p>
                {% elif section.type == "bullets" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.items %}
                    <ul class="bullet-list">
                        {% for item in section.items %}<li>{{ item | safe }}</li>{% endfor %}
                    </ul>
                    {% endif %}
                {% else %}
                    <p>{{ section.content | safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% if team and team | length > 0 %}
        <div class="section">
            <h2>The Team</h2>
            <div class="section-content">
                <div class="team-grid">
                    {% for member in team %}
                    <div class="team-member">
                        <p class="name">{{ member.name }}</p>
                        <p class="role">{{ member.role }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        {% if ask %}
        <div class="section">
            <h2>The Ask</h2>
            <div class="section-content">
                <div class="highlight-box"><p style="font-size: 1.2rem;">{{ ask }}</p></div>
            </div>
        </div>
        {% endif %}

        <div class="document-footer">
            <p>{{ footer_text | default("Generated by Kai AI") }}</p>
        </div>
    </div>
</body>
</html>'''

# ===================== TECHNICAL GUIDE =====================
technical_guide = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Technical Guide</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    <style>{{ css_content }}</style>
    {% if accent_color %}
    <style>:root { --primary: {{ accent_color }}; --primary-dark: {{ accent_color }}; }</style>
    {% endif %}
</head>
<body>
    <div class="document">
        <div class="cover-page">
            <h1 class="title">{{ title }}</h1>
            {% if subtitle %}<p class="subtitle">{{ subtitle }}</p>{% endif %}
            <div class="brand-accent"></div>
            {% if tech_stack and tech_stack | length > 0 %}
            <div class="tech-stack" style="justify-content: center; margin-top: 2rem;">
                {% for tech in tech_stack %}<span class="tech-badge">{{ tech }}</span>{% endfor %}
            </div>
            {% endif %}
            <div class="meta">
                <p class="author">{{ author | default("Kai AI") }}</p>
                <p class="date">{{ date }}</p>
            </div>
        </div>

        {% if overview %}
        <div class="section">
            <h2>Overview</h2>
            <div class="section-content"><p>{{ overview }}</p></div>
        </div>
        {% endif %}

        {% if prerequisites and prerequisites | length > 0 %}
        <div class="section">
            <h2>Prerequisites</h2>
            <div class="section-content">
                <ul class="bullet-list">
                    {% for prereq in prerequisites %}<li>{{ prereq }}</li>{% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% if architecture_notes %}
        <div class="section">
            <h2>Architecture</h2>
            <div class="section-content"><p>{{ architecture_notes | safe }}</p></div>
        </div>
        {% endif %}

        {% for section in sections %}
        <div class="section">
            {% if section.heading %}<h2>{{ section.heading }}</h2>{% endif %}
            <div class="section-content">
                {% if section.type == "paragraph" %}
                    {{ section.content | safe }}
                {% elif section.type == "bullets" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.items %}
                    <ul class="bullet-list">
                        {% for item in section.items %}<li>{{ item | safe }}</li>{% endfor %}
                    </ul>
                    {% endif %}
                {% elif section.type == "table" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.data and section.data | length > 0 %}
                    <table>
                        <thead><tr>{% for h in section.data[0] %}<th>{{ h }}</th>{% endfor %}</tr></thead>
                        <tbody>{% for row in section.data[1:] %}<tr>{% for cell in row %}<td>{{ cell }}</td>{% endfor %}</tr>{% endfor %}</tbody>
                    </table>
                    {% endif %}
                {% elif section.type == "highlight" %}
                    <div class="highlight-box"><p>{{ section.content | safe }}</p></div>
                {% else %}
                    <p>{{ section.content | safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% if highlights and highlights | length > 0 %}
        <div class="section">
            <h2>Key Takeaways</h2>
            <div class="section-content">
                <div class="highlight-box">
                    {% for highlight in highlights %}<div class="highlight-item">{{ highlight }}</div>{% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="document-footer">
            <p>{{ footer_text | default("Generated by Kai AI") }}</p>
        </div>
    </div>
</body>
</html>'''

# ===================== EXPO SUBMISSION =====================
expo_submission = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Expo Submission</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>{{ css_content }}</style>
    {% if accent_color %}
    <style>:root { --primary: {{ accent_color }}; --primary-dark: {{ accent_color }}; }</style>
    {% endif %}
</head>
<body>
    <div class="document">
        <div class="cover-page">
            <h1 class="title">{{ title }}</h1>
            {% if tagline %}<p class="tagline">"{{ tagline }}"</p>{% endif %}
            <div class="brand-accent"></div>
            <div class="meta">
                <p class="author">{{ author | default("Kai AI") }}</p>
                <p class="date">{{ date }}</p>
            </div>
        </div>

        {% if problem_statement %}
        <div class="section">
            <h2>The Problem</h2>
            <div class="section-content"><p>{{ problem_statement }}</p></div>
        </div>
        {% endif %}

        {% if solution_overview %}
        <div class="section">
            <h2>Our Solution</h2>
            <div class="section-content"><p>{{ solution_overview }}</p></div>
        </div>
        {% endif %}

        {% if key_features and key_features | length > 0 %}
        <div class="section">
            <h2>Key Features</h2>
            <div class="section-content">
                <ul class="bullet-list">
                    {% for feature in key_features %}<li>{{ feature }}</li>{% endfor %}
                </ul>
            </div>
        </div>
        {% endif %}

        {% if tech_stack and tech_stack | length > 0 %}
        <div class="section">
            <h2>Tech Stack</h2>
            <div class="section-content">
                <div class="tech-stack">
                    {% for tech in tech_stack %}<span class="tech-badge">{{ tech }}</span>{% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        {% if target_users %}
        <div class="section">
            <h2>Target Users</h2>
            <div class="section-content"><p>{{ target_users }}</p></div>
        </div>
        {% endif %}

        {% if impact_metrics %}
        <div class="section">
            <h2>Impact Metrics</h2>
            <div class="section-content">
                <div class="metrics-grid">
                    {% for label, value in impact_metrics.items() %}
                    <div class="metric-card">
                        <div class="metric-value">{{ value }}</div>
                        <div class="metric-label">{{ label }}</div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        {% for section in sections %}
        <div class="section">
            {% if section.heading %}<h2>{{ section.heading }}</h2>{% endif %}
            <div class="section-content">
                {% if section.type == "paragraph" %}
                    <p>{{ section.content | safe }}</p>
                {% elif section.type == "bullets" %}
                    {% if section.content %}<p>{{ section.content | safe }}</p>{% endif %}
                    {% if section.items %}
                    <ul class="bullet-list">
                        {% for item in section.items %}<li>{{ item | safe }}</li>{% endfor %}
                    </ul>
                    {% endif %}
                {% else %}
                    <p>{{ section.content | safe }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% if team and team | length > 0 %}
        <div class="section">
            <h2>The Team</h2>
            <div class="section-content">
                <div class="team-grid">
                    {% for member in team %}
                    <div class="team-member">
                        <p class="name">{{ member.name }}</p>
                        <p class="role">{{ member.role }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endif %}

        <div class="document-footer">
            <p>{{ footer_text | default("Generated by Kai AI") }}</p>
        </div>
    </div>
</body>
</html>'''

# ===================== WRITE ALL TEMPLATES =====================
templates = {
    "professional_report.html": professional_report,
    "pitch_document.html": pitch_document,
    "technical_guide.html": technical_guide,
    "expo_submission.html": expo_submission
}

for filename, content in templates.items():
    filepath = os.path.join(TEMPLATE_DIR, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Fixed: {filename}")

# Verify all templates
print("\n=== Verification ===")
for filename in templates.keys():
    filepath = os.path.join(TEMPLATE_DIR, filename)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        if "{{ css_content }}" in content and "section.items" in content:
            print(f"✓ {filename}: OK")
        else:
            print(f"✗ {filename}: FAILED")

print("\nDone! Restart the API server to apply changes.")
