import os
import json
import time
import random
import re
import subprocess
from typing import Dict, Any, List
from dotenv import dotenv_values
from PIL import Image, ImageDraw, ImageFont

try:
    from Backend.RealtimeSearchEngine import RealtimeSearchEngine
except ImportError:
    from RealtimeSearchEngine import RealtimeSearchEngine
try:
    from Backend.TextToSpeech import TextToAudioFile
except ImportError:
    from TextToSpeech import TextToAudioFile


class YoutubeAutomation:
    """High-level YouTube automation pipeline (research -> content -> upload stubs)."""

    def __init__(self):
        current_dir = os.path.dirname(os.path.abspath(__file__))
        self.project_root = os.path.dirname(current_dir)
        self.data_dir = os.path.join(self.project_root, "Data")
        os.makedirs(self.data_dir, exist_ok=True)
        self.logs_dir = os.path.join(self.project_root, "logs")
        os.makedirs(self.logs_dir, exist_ok=True)

    # ---------------------- Research ----------------------
    def research_topics(self, niche: str) -> Dict[str, Any]:
        queries = [
            f"latest news in {niche}",
            f"trending {niche} topics",
            f"top news in {niche}",
        ]
        findings: List[str] = []
        for q in queries:
            try:
                ans = RealtimeSearchEngine(q)
                if ans:
                    findings.append(ans)
            except Exception:
                pass
            time.sleep(0.2)
        summary = "\n\n".join(findings)[:2500]
        return {"niche": niche, "findings": findings, "summary": summary}

    # ---------------------- Content ----------------------
    def draft_script(self, research: Dict[str, Any]) -> str:
        niche = research.get("niche", "topic")
        base = research.get("summary", "")
        outline = [
            f"Hook: Why {niche} is exploding right now",
            "Context: What changed this week",
            "3 key points with examples",
            "Actionable takeaway",
            "Outro with CTA"
        ]
        script = f"Title idea: {niche.title()} — What You Need To Know Right Now\n\n"
        script += "\n".join(f"- {p}" for p in outline)
        if base:
            script += f"\n\nNotes:\n{base[:1200]}"
        return script

    def suggest_title_tags_desc(self, research: Dict[str, Any]) -> Dict[str, Any]:
        niche = research.get("niche", "topic")
        title = f"{niche.title()} Update: Top Stories You Missed"
        tags = [niche, f"{niche} news", "explained", "trending", "update"]
        desc = f"Quick update on {niche}. Auto-generated by AI assistant.\n#shorts #news #{niche.replace(' ', '')}"
        return {"title": title, "tags": tags, "description": desc}

    def generate_chapters_and_hashtags(self, research: Dict[str, Any]) -> Dict[str, Any]:
        niche = research.get("niche", "topic")
        # simple static chapters
        chapters = [
            {"time": "00:00", "title": "Intro"},
            {"time": "00:30", "title": "Key Updates"},
            {"time": "01:30", "title": "Why It Matters"},
            {"time": "02:00", "title": "Takeaways"},
        ]
        hashtags = [f"#{niche.replace(' ', '')}", "#news", "#trending", "#update"]
        return {"chapters": chapters, "hashtags": hashtags}

    # ---------------------- Upload stubs ----------------------
    def render_stub(self, script: str) -> str:
        path = os.path.join(self.data_dir, "render_stub.txt")
        with open(path, "w", encoding="utf-8") as f:
            f.write(script)
        return path

    # ---------------------- Media generation ----------------------
    def generate_thumbnail(self, title: str) -> str:
        w, h = 1280, 720
        img = Image.new("RGB", (w, h), color=(20, 20, 20))
        draw = ImageDraw.Draw(img)
        # Simple gradient bars
        for i in range(0, h, 8):
            shade = 20 + int(80 * (i / h))
            draw.rectangle([0, i, w, i + 8], fill=(shade, 30, 80))
        # Title text
        text = title[:70]
        try:
            font = ImageFont.truetype("arial.ttf", 64)
        except Exception:
            font = ImageFont.load_default()
        try:
            tw, th = font.getsize(text)
        except Exception:
            tw, th = (min(len(text) * 20, w - 40), 80)
        draw.text(((w - tw) / 2, (h - th) / 2), text, fill=(255, 255, 255), font=font)
        out = os.path.join(self.data_dir, "thumbnail.png")
        img.save(out, format="PNG")
        return out

    def generate_thumbnail_variants(self, title: str, k: int = 3) -> List[str]:
        outputs = []
        for i in range(k):
            try:
                path = self.generate_thumbnail(f"{title} #{i+1}")
                outputs.append(path)
            except Exception:
                pass
        return outputs or [self.generate_thumbnail(title)]

    def score_thumbnail(self, path: str) -> float:
        # naive: prefer images that exist and have expected size
        try:
            img = Image.open(path)
            w, h = img.size
            score = 0.0
            if w == 1280 and h == 720:
                score += 0.5
            score += random.random() * 0.5
            return score
        except Exception:
            return 0.0

    async def synthesize_voice(self, script: str) -> str:
        # Use existing async TTS to create mp3
        audio_path = os.path.join(self.data_dir, "speech.mp3")
        ok = await TextToAudioFile(script)
        return audio_path if ok else ""

    def render_simple_video(self, image_path: str, audio_path: str) -> str:
        out_path = os.path.join(self.data_dir, "video.mp4")
        if not os.path.exists(image_path) or not os.path.exists(audio_path):
            return ""
        cmd = [
            "ffmpeg", "-y", "-loop", "1", "-i", image_path,
            "-i", audio_path,
            "-c:v", "libx264", "-tune", "stillimage",
            "-c:a", "aac", "-b:a", "192k",
            "-pix_fmt", "yuv420p",
            "-shortest", out_path
        ]
        try:
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return out_path
        except Exception:
            return ""

    def upload_stub(self, meta: Dict[str, Any]) -> bool:
        # Placeholder for YouTube API integration
        log = {"event": "upload_stub", "meta": meta, "ts": time.time()}
        with open(os.path.join(self.logs_dir, "youtube_automation.log"), "a", encoding="utf-8") as f:
            f.write(json.dumps(log) + "\n")
        return True

    # Placeholder for real YouTube Data API upload (OAuth to be configured)
    def youtube_api_upload(self, video_path: str, meta: Dict[str, Any]) -> bool:
        log = {"event": "youtube_api_upload_placeholder", "video": video_path, "meta": meta, "ts": time.time()}
        with open(os.path.join(self.logs_dir, "youtube_automation.log"), "a", encoding="utf-8") as f:
            f.write(json.dumps(log) + "\n")
        return bool(video_path)

    def schedule_stub(self, meta: Dict[str, Any], when_iso: str) -> bool:
        entry = {"event": "schedule_stub", "when": when_iso, "meta": meta, "ts": time.time()}
        with open(os.path.join(self.logs_dir, "youtube_automation.log"), "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
        # Persist a simple schedules file
        sched_path = os.path.join(self.data_dir, "yt_schedules.json")
        try:
            schedules = []
            if os.path.exists(sched_path):
                with open(sched_path, "r", encoding="utf-8") as rf:
                    schedules = json.load(rf)
            schedules.append(entry)
            with open(sched_path, "w", encoding="utf-8") as wf:
                json.dump(schedules, wf, indent=2)
        except Exception:
            pass
        return True

    def cross_post_stub(self, video_path: str, meta: Dict[str, Any]) -> bool:
        entry = {"event": "cross_post_stub", "destinations": ["shorts", "reels", "tiktok"], "video": video_path, "meta": meta, "ts": time.time()}
        with open(os.path.join(self.logs_dir, "youtube_automation.log"), "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
        return True

    # ---------------------- Orchestrate ----------------------
    def run_once(self, niche: str) -> Dict[str, Any]:
        research = self.research_topics(niche)
        script = self.draft_script(research)
        meta = self.suggest_title_tags_desc(research)
        aug = self.generate_chapters_and_hashtags(research)
        # augment description with chapters and hashtags
        if meta:
            chapter_lines = [f"{c['time']} - {c['title']}" for c in aug.get("chapters", [])]
            meta["description"] += "\n\nChapters:\n" + "\n".join(chapter_lines)
            meta["description"] += "\n\nHashtags: " + " ".join(aug.get("hashtags", []))
        artifact = self.render_stub(script)
        # Produce thumbnail variants and pick best
        thumb = ""
        best_score = -1.0
        for p in self.generate_thumbnail_variants(meta["title"]) if meta else []:
            s = self.score_thumbnail(p)
            if s > best_score:
                best_score = s
                thumb = p
        # Try voice + video (best-effort)
        video_path = ""
        try:
            import asyncio
            audio_path = asyncio.run(self.synthesize_voice(script))
            if audio_path:
                video_path = self.render_simple_video(thumb or artifact, audio_path)
        except Exception:
            pass
        # Attempt API upload placeholder (logs) then stub
        if video_path:
            self.youtube_api_upload(video_path, meta)
        uploaded = self.upload_stub(meta)
        result = {"research": research, "script_path": artifact, "thumbnail_path": thumb, "video_path": video_path, "meta": meta, "uploaded": uploaded}
        with open(os.path.join(self.data_dir, f"yt_{niche.replace(' ', '_')}.json"), "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
        return result

    # Convenience wrappers
    def upload_now(self, niche: str) -> bool:
        res = self.run_once(niche)
        # In real integration, replace stub with YouTube Data API upload here
        return bool(res)

    def schedule(self, niche: str, when_iso: str) -> bool:
        research = self.research_topics(niche)
        meta = self.suggest_title_tags_desc(research)
        return self.schedule_stub(meta, when_iso)


if __name__ == "__main__":
    ya = YoutubeAutomation()
    out = ya.run_once("ai")
    print(json.dumps(out, indent=2))


