"""
Document Schemas - Structured Content Definitions
==================================================
Defines strict schemas for each document type.
LLM must output content matching these schemas.
"""

from typing import TypedDict, List, Optional, Dict, Any, Literal
from dataclasses import dataclass
from enum import Enum

class DocumentType(Enum):
    EXPO_SUBMISSION = "expo_submission"
    PITCH_DOCUMENT = "pitch_document"
    TECHNICAL_GUIDE = "technical_guide"
    PROFESSIONAL_REPORT = "professional_report"

# Available document types
DOCUMENT_TYPES = [dt.value for dt in DocumentType]

# === SECTION TYPES ===

class Section(TypedDict, total=False):
    """A content section within a document."""
    heading: str
    content: str  # Paragraph text
    type: Literal["paragraph", "bullets", "table", "highlight", "two_column"]
    items: List[str]  # For bullets
    data: List[List[str]]  # For tables [[header], [row1], [row2]]
    left_content: str  # For two_column
    right_content: str  # For two_column

class TeamMember(TypedDict):
    name: str
    role: str

# === BASE DOCUMENT SCHEMA ===

class DocumentSchema(TypedDict, total=False):
    """
    Unified document schema that all document types extend.
    This is the contract between LLM output and template rendering.
    """
    # Required fields
    document_type: str
    title: str
    
    # Common optional fields
    subtitle: Optional[str]
    author: str
    date: str
    sections: List[Section]
    
    # Document-specific fields
    tagline: Optional[str]  # expo, pitch
    problem_statement: Optional[str]  # expo
    solution_overview: Optional[str]  # expo
    key_features: Optional[List[str]]  # expo, pitch
    tech_stack: Optional[List[str]]  # expo, technical
    target_users: Optional[str]  # expo
    impact_metrics: Optional[Dict[str, str]]  # expo
    team: Optional[List[TeamMember]]  # expo, pitch
    
    # Pitch-specific
    vision: Optional[str]
    market_size: Optional[str]
    traction: Optional[List[str]]
    ask: Optional[str]  # What you're asking for
    
    # Technical guide specific
    overview: Optional[str]
    prerequisites: Optional[List[str]]
    architecture_notes: Optional[str]
    
    # Common styling
    highlights: Optional[List[str]]  # Key callouts/quotes
    footer_text: Optional[str]
    accent_color: Optional[str]  # Hex color

# === VALIDATION ===

REQUIRED_FIELDS = {
    "expo_submission": ["title", "problem_statement", "solution_overview", "key_features"],
    "pitch_document": ["title", "vision", "sections"],
    "technical_guide": ["title", "overview", "sections"],
    "professional_report": ["title", "sections"]
}

def validate_schema(data: Dict[str, Any], document_type: str) -> Dict[str, Any]:
    """
    Validate and normalize document data.
    Returns cleaned data with defaults filled in.
    Raises ValueError if required fields are missing.
    """
    if document_type not in DOCUMENT_TYPES:
        raise ValueError(f"Unknown document type: {document_type}. Must be one of {DOCUMENT_TYPES}")
    
    # Ensure document_type is set
    data["document_type"] = document_type
    
    # Check required fields
    required = REQUIRED_FIELDS.get(document_type, ["title", "sections"])
    missing = [f for f in required if not data.get(f)]
    
    if missing:
        raise ValueError(f"Missing required fields for {document_type}: {missing}")
    
    # Set defaults
    data.setdefault("author", "Kai AI")
    data.setdefault("date", "")  # Will be filled by renderer
    data.setdefault("sections", [])
    data.setdefault("footer_text", "Generated by Kai AI")
    data.setdefault("accent_color", "#2563EB")  # Royal Blue
    
    # Normalize sections
    for section in data.get("sections", []):
        section.setdefault("type", "paragraph")
        section.setdefault("items", [])
        section.setdefault("data", [])
    
    return data

# === SCHEMA PROMPTS FOR LLM ===

SCHEMA_PROMPTS = {
    "expo_submission": """
Generate COMPREHENSIVE content for an AI Expo/Conference Submission (3-4 pages worth).
Return ONLY valid JSON:
{
    "title": "Project Title - Make it catchy and memorable",
    "tagline": "One-line hook that captures the essence (max 15 words)",
    "problem_statement": "Write 3-4 detailed sentences explaining the pain point. Be specific about who suffers and how. Include statistics if relevant. Make the reader feel the problem.",
    "solution_overview": "Write 3-4 detailed sentences about your unique approach. Explain the core innovation and why it works better than alternatives.",
    "key_features": [
        "Feature 1 - with brief explanation of benefit",
        "Feature 2 - with brief explanation of benefit", 
        "Feature 3 - with brief explanation of benefit",
        "Feature 4 - with brief explanation of benefit",
        "Feature 5 - with brief explanation of benefit",
        "Feature 6 - with brief explanation of benefit"
    ],
    "tech_stack": ["Technology1", "Technology2", "Technology3", "Technology4", "Technology5"],
    "target_users": "Write 2-3 sentences describing primary user personas, their needs, and how they benefit.",
    "impact_metrics": {
        "Metric 1": "Value with context",
        "Metric 2": "Value with context",
        "Metric 3": "Value with context",
        "Metric 4": "Value with context"
    },
    "team": [
        {"name": "Team Lead Name", "role": "Lead Developer / Architect"},
        {"name": "Member 2", "role": "ML Engineer"},
        {"name": "Member 3", "role": "Frontend Developer"}
    ],
    "sections": [
        {"heading": "Technical Innovation", "content": "Write 2-3 paragraphs (200+ words) explaining the technical approach, algorithms used, and what makes this innovative.", "type": "paragraph"},
        {"heading": "Implementation Details", "content": "Write 2 paragraphs about how the system works, architecture decisions, and key components.", "type": "paragraph"},
        {"heading": "Demo & Results", "content": "", "type": "bullets", "items": ["Result 1 with specific numbers", "Result 2 with comparison", "Result 3 with impact measurement", "Result 4 with user feedback"]},
        {"heading": "Future Roadmap", "content": "", "type": "bullets", "items": ["Q1: Major milestone with details", "Q2: Enhancement with details", "Q3: Expansion with details", "Q4: Long-term vision"]}
    ]
}
""",

    "pitch_document": """
Generate COMPREHENSIVE content for a Startup Pitch Document (3-4 pages worth).
Return ONLY valid JSON:
{
    "title": "Company/Product Name",
    "tagline": "One-line value proposition that hooks investors",
    "vision": "Write 3-4 sentences painting a compelling picture of the future you're building. Be ambitious but credible.",
    "problem_statement": "Write 3-4 sentences about the market problem. Include market size pain points. Make investors feel the opportunity.",
    "solution_overview": "Write 3-4 sentences about your unique solution. Explain your unfair advantage and moat.",
    "market_size": "TAM: $X billion. SAM: $X billion. SOM: $X million. Include growth rates and cite sources if possible.",
    "traction": [
        "Achievement 1: specific numbers (e.g., '10,000 users in 3 months')",
        "Achievement 2: key partnerships or customers",
        "Achievement 3: revenue or engagement metrics",
        "Achievement 4: notable press or recognition",
        "Achievement 5: product milestones"
    ],
    "key_features": [
        "Differentiator 1 - why this matters",
        "Differentiator 2 - why this matters",
        "Differentiator 3 - why this matters",
        "Differentiator 4 - why this matters"
    ],
    "ask": "Write 2-3 sentences: How much you're raising, what you'll use it for, expected milestones.",
    "team": [
        {"name": "Founder Name", "role": "CEO - background highlights"},
        {"name": "Co-founder", "role": "CTO - background highlights"},
        {"name": "Key Hire", "role": "Role - why they matter"}
    ],
    "sections": [
        {"heading": "Business Model", "content": "Write 2-3 paragraphs (200+ words) explaining how you make money, pricing strategy, unit economics.", "type": "paragraph"},
        {"heading": "Go-To-Market Strategy", "content": "Write 2 paragraphs about customer acquisition, channels, and growth strategy.", "type": "paragraph"},
        {"heading": "Competitive Landscape", "content": "Write 1 paragraph intro", "type": "bullets", "items": ["Competitor 1: their weakness, your advantage", "Competitor 2: their weakness, your advantage", "Your Moat: why you win"]},
        {"heading": "Financial Projections", "content": "", "type": "table", "data": [["Year", "Revenue", "Users", "Margin"], ["Year 1", "$X", "X", "X%"], ["Year 2", "$X", "X", "X%"], ["Year 3", "$X", "X", "X%"]]}
    ]
}
""",

    "technical_guide": """
Generate COMPREHENSIVE content for a Technical Guide/Whitepaper (4-5 pages worth).
Return ONLY valid JSON:
{
    "title": "Clear Technical Title",
    "subtitle": "Comprehensive guide to...",
    "overview": "Write 3-4 sentences explaining what this guide covers, who it's for, and what readers will learn.",
    "prerequisites": [
        "Prerequisite 1 with version if relevant",
        "Prerequisite 2 with version if relevant",
        "Prerequisite 3",
        "Prerequisite 4"
    ],
    "tech_stack": ["Technology1", "Technology2", "Technology3", "Technology4"],
    "sections": [
        {"heading": "Introduction", "content": "Write 2-3 paragraphs (200+ words) introducing the topic, its importance, and real-world applications.", "type": "paragraph"},
        {"heading": "Core Concepts", "content": "Write 2 paragraphs explaining fundamental concepts the reader needs to understand.", "type": "paragraph"},
        {"heading": "Architecture Overview", "content": "Write 2 paragraphs explaining the system architecture, components, and how they interact.", "type": "paragraph"},
        {"heading": "Implementation Steps", "content": "Follow these steps to implement:", "type": "bullets", "items": ["Step 1: Detailed instruction with explanation", "Step 2: Detailed instruction with explanation", "Step 3: Detailed instruction with explanation", "Step 4: Detailed instruction with explanation", "Step 5: Detailed instruction with explanation", "Step 6: Final verification steps"]},
        {"heading": "Configuration", "content": "", "type": "table", "data": [["Parameter", "Default", "Description"], ["param1", "value", "What it does"], ["param2", "value", "What it does"], ["param3", "value", "What it does"]]},
        {"heading": "Best Practices", "content": "", "type": "bullets", "items": ["Practice 1: Why and how", "Practice 2: Why and how", "Practice 3: Why and how", "Practice 4: Why and how", "Practice 5: Why and how"]},
        {"heading": "Troubleshooting", "content": "", "type": "bullets", "items": ["Issue 1: Solution", "Issue 2: Solution", "Issue 3: Solution"]},
        {"heading": "Conclusion", "content": "Write 2 paragraphs summarizing key points and suggesting next steps for learning.", "type": "paragraph"}
    ],
    "highlights": ["Key insight 1 - major takeaway", "Key insight 2 - important concept", "Key insight 3 - practical advice"]
}
""",

    "professional_report": """
Generate COMPREHENSIVE content for a Professional Report (4-5 pages worth).
Return ONLY valid JSON:
{
    "title": "Report Title - Clear and Descriptive",
    "subtitle": "Subtitle or date range or context",
    "sections": [
        {"heading": "Executive Summary", "content": "Write 3-4 paragraphs (250+ words) providing a complete high-level overview. Cover the purpose, methodology, key findings, and primary recommendations. This should stand alone for busy executives.", "type": "paragraph"},
        {"heading": "Introduction", "content": "Write 2-3 paragraphs explaining the background, context, and objectives of this report.", "type": "paragraph"},
        {"heading": "Methodology", "content": "Write 1-2 paragraphs explaining how data was gathered and analyzed.", "type": "paragraph"},
        {"heading": "Analysis", "content": "Write 3-4 paragraphs (300+ words) providing detailed analysis of the subject matter. Include specific data points, trends, and observations.", "type": "paragraph"},
        {"heading": "Key Findings", "content": "The analysis reveals several critical insights:", "type": "bullets", "items": ["Finding 1: Detailed explanation with data (2-3 sentences)", "Finding 2: Detailed explanation with data (2-3 sentences)", "Finding 3: Detailed explanation with data (2-3 sentences)", "Finding 4: Detailed explanation with data (2-3 sentences)", "Finding 5: Detailed explanation with data (2-3 sentences)"]},
        {"heading": "Data Overview", "content": "", "type": "table", "data": [["Metric", "Current", "Previous", "Change"], ["Metric 1", "Value", "Value", "+X%"], ["Metric 2", "Value", "Value", "+X%"], ["Metric 3", "Value", "Value", "+X%"], ["Metric 4", "Value", "Value", "+X%"]]},
        {"heading": "Recommendations", "content": "Based on our analysis, we recommend:", "type": "bullets", "items": ["Recommendation 1: Action + expected impact (2-3 sentences)", "Recommendation 2: Action + expected impact (2-3 sentences)", "Recommendation 3: Action + expected impact (2-3 sentences)", "Recommendation 4: Action + expected impact (2-3 sentences)"]},
        {"heading": "Implementation Timeline", "content": "", "type": "table", "data": [["Phase", "Timeline", "Deliverables"], ["Phase 1", "Weeks 1-2", "Initial setup and assessment"], ["Phase 2", "Weeks 3-4", "Core implementation"], ["Phase 3", "Weeks 5-6", "Testing and optimization"]]},
        {"heading": "Conclusion", "content": "Write 2-3 paragraphs summarizing the key points, reiterating the most important recommendations, and outlining next steps.", "type": "paragraph"}
    ],
    "highlights": ["Key takeaway 1 - most important insight", "Key takeaway 2 - critical action item", "Key takeaway 3 - strategic consideration"]
}
"""
}

def get_schema_prompt(document_type: str, topic: str) -> str:
    """Get the LLM prompt for generating content of a specific document type."""
    base_prompt = SCHEMA_PROMPTS.get(document_type, SCHEMA_PROMPTS["professional_report"])
    return f"""
You are an expert content creator writing about: "{topic}"

{base_prompt}

CRITICAL REQUIREMENTS:
1. Return ONLY valid JSON - no markdown, no code blocks, no extra text
2. Make content DETAILED and COMPREHENSIVE - aim for 1500+ words total
3. Each paragraph section should be 200-400 words with real substance
4. Use specific numbers, statistics, and examples where possible
5. Write in professional but engaging tone
6. Avoid placeholder text like "..." - write real content
7. Each bullet point should be 1-2 complete sentences
8. Tables should have realistic, specific data

Topic: {topic}
Generate the complete document now:
"""

